theme = "catppuccin_macchiato"

[editor]
cursorline = true
color-modes = true
true-color = true
auto-format = true
auto-completion = true
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.file-picker]
hidden = false

[editor.cursor-shape]
normal = "block"
insert = "block"
select = "underline"

[editor.soft-wrap]
enable = true

[editor.lsp]
enable = true
display-messages = true
display-inlay-hints = true

[editor.indent-guides]
render = true
character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
skip-levels = 1

# I want to be able to go back to normal mode keeping fingers on home row, so
# putting an Emacs-y keybinding for that.
[keys.insert]
C-e = "insert_at_line_end"
C-a = "insert_at_line_start"
C-n = "move_visual_line_down"
C-p = "move_visual_line_up"
C-m = [":write-all", "normal_mode"]
C-b = "move_char_left"
C-f = "move_char_right"
C-x = { C-s = [":write-all", "normal_mode"], s = [":write-all", "normal_mode"] }

[keys.normal]
# Under the influence of:
# https://felix-knorr.net/posts/2025-03-16-helix-review.html
"ret" = "goto_word"
# Prints the current line's git blame information to the statusline.
"B" = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
C-r = ":reload-all"
C-m = ":write-all"
C-x = { C-s = ":write-all",  s = ":write-all" }

[editor.statusline]
left = [
  "mode",
  "spinner",
  "file-name",
  "separator",
  "spacer",
  "version-control",
  "read-only-indicator",
  "file-modification-indicator",

]
center = []
right = [
  "diagnostics",
  "workspace-diagnostics",
  "position",
  "total-line-numbers",
  "position-percentage",
  "file-encoding",
  "file-line-ending",
  "file-type",
  "register",
  "selections",
]
separator = "│"
